server:
  port: 8080

spring:
  datasource:
    # 连你自己电脑的 MySQL
    url: jdbc:mysql://127.0.0.1:3306/ai_mall?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: your_username  # 你的本地数据库用户名
    password: your_password  # 你的本地密码
  redis:
    # 你的公网测试 Redis
    host: 127.0.0.1
    port: 6379
    password: your_redis_password #如果 Redis 没有密码，可以注释掉这一行
    timeout: 2000ms

aimall:
  llm:
    # 填你自己申请的阿里百炼 API Key
    api-key:
  embedding:
    api-key: