<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>cn.vetech.ai</groupId>
        <artifactId>ai-search-parent</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>ai-search-feign</artifactId>
    <packaging>jar</packaging>
    <name>AI Search Feign</name>
    <description>公司远程服务客户端：商品服务/权限/LLM API（预留）</description>

    <dependencies>
        <dependency>
            <groupId>cn.vetech.ai</groupId>
            <artifactId>ai-search-fccapi</artifactId>
        </dependency>
    </dependencies>

</project>
