#!/usr/bin/env python3
"""Shared validation helpers for the Doccano NER workflow."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple


NER_LABELS = {
    "CATEGORY",
    "BRAND",
    "PRODUCT_TYPE",
    "SCENE",
    "ATTRIBUTE_VALUE",
}


def read_jsonl(path: Path) -> Iterable[Tuple[int, Dict[str, Any]]]:
    with path.open("r", encoding="utf-8-sig") as source:
        for line_number, raw_line in enumerate(source, 1):
            line = raw_line.strip()
            if not line:
                continue
            try:
                record = json.loads(line)
            except json.JSONDecodeError as exc:
                raise ValueError(
                    f"{path}:{line_number} is not valid JSON: {exc.msg}"
                ) from exc
            if not isinstance(record, dict):
                raise ValueError(f"{path}:{line_number} must be a JSON object")
            yield line_number, record


def write_jsonl(path: Path, records: Iterable[Dict[str, Any]]) -> int:
    path.parent.mkdir(parents=True, exist_ok=True)
    count = 0
    with path.open("w", encoding="utf-8", newline="\n") as target:
        for record in records:
            target.write(json.dumps(record, ensure_ascii=False, sort_keys=True) + "\n")
            count += 1
    return count


def query_id_from_record(
    record: Dict[str, Any],
    *,
    allow_doccano_id_fallback: bool = False,
) -> str:
    meta = record.get("meta")
    if isinstance(meta, dict):
        query_id = str(meta.get("query_id", "")).strip()
        if query_id:
            return query_id

    if allow_doccano_id_fallback:
        doccano_id = record.get("doc_id", record.get("id"))
        if doccano_id is not None and str(doccano_id).strip():
            return f"doccano:{str(doccano_id).strip()}"

    raise ValueError(
        "record is missing meta.query_id; re-import tasks generated by "
        "data_build_annotation_tasks.py, or explicitly allow the unstable "
        "Doccano id fallback"
    )


def approved_by(record: Dict[str, Any]) -> Optional[str]:
    for field in ("annotation_approver", "approved_by", "approver"):
        value = record.get(field)
        if value is not None and str(value).strip():
            return str(value).strip()
    return None


def entities_from_record(record: Dict[str, Any]) -> List[Dict[str, Any]]:
    text = record.get("text")
    if not isinstance(text, str) or not text.strip():
        raise ValueError("record.text must be a non-empty string")

    raw_labels = record.get("labels")
    if raw_labels is None:
        raw_labels = record.get("label", [])
    if raw_labels is None:
        raw_labels = []
    if not isinstance(raw_labels, list):
        raise ValueError("record.labels must be a list")

    entities: List[Dict[str, Any]] = []
    for index, raw_label in enumerate(raw_labels):
        if not isinstance(raw_label, Sequence) or isinstance(raw_label, (str, bytes)):
            raise ValueError(f"labels[{index}] must be [start, end, label]")
        if len(raw_label) != 3:
            raise ValueError(f"labels[{index}] must contain exactly three values")
        start, end, label = raw_label
        if isinstance(start, bool) or not isinstance(start, int):
            raise ValueError(f"labels[{index}].start must be an integer")
        if isinstance(end, bool) or not isinstance(end, int):
            raise ValueError(f"labels[{index}].end must be an integer")
        label = str(label).strip()
        if label not in NER_LABELS:
            raise ValueError(
                f"labels[{index}] has unsupported label {label!r}; "
                f"allowed labels: {', '.join(sorted(NER_LABELS))}"
            )
        if start < 0 or end <= start or end > len(text):
            raise ValueError(
                f"labels[{index}] has invalid span [{start}, {end}) "
                f"for text length {len(text)}"
            )
        entities.append(
            {
                "start": start,
                "end": end,
                "label": label,
                "text": text[start:end],
            }
        )

    entities.sort(key=lambda item: (item["start"], item["end"], item["label"]))
    for previous, current in zip(entities, entities[1:]):
        if current["start"] < previous["end"]:
            raise ValueError(
                "overlapping entities are not allowed: "
                f"[{previous['start']}, {previous['end']}) and "
                f"[{current['start']}, {current['end']})"
            )
    return entities


def entity_key(entity: Dict[str, Any]) -> Tuple[int, int, str]:
    return int(entity["start"]), int(entity["end"]), str(entity["label"])
